version: "3.4"
services:
  mymusicapi:
    image: "mymusicback"
    restart: always
    environment:
      ASPNETCORE_URLS: "http://+"
      KESTREL__ENDPOINTS__HTTP__URL: http://[::]:5300
    ports:
     - 5300:5300
  mymusiclient:
    image: "mymusicclient3"
    restart: always
    environment:
      MYMUSICAPI: "http://mymusicapi:5300/api/"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
     - 5100:80